CREATE DATABASE IF NOT EXISTS `db`;
CREATE TABLE IF NOT EXISTS `db`.`m_user`(
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;